server:
  port: 8080   # Your server port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | create-drop | update | validate | none
    show-sql: true       # To print SQL queries in console
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jpa.properties.hibernate:
    globally_quoted_identifiers: true
